### ISSUE TITLE
Fetch aggregated data instead of full datasets for hive and discussion counts

### ISSUE THREAD

**Issue by mrow4a** [paperhive/paperhive-widget#31]
Looking in the function call of `fetch()` in https://github.com/paperhive/paperhive-widget/blob/master/src/index.js#L25, and getting a response in a format of very very long JSON array structure - e.g. https://paperhive.org/api/documents/Ra5WnkxImoOE/discussions, and then doing https://github.com/paperhive/paperhive-widget/blob/master/src/index.js#L44 (which in practice checks array lenght) is also very inefficient for big number of discussions. 

This is because JSON has to be parsed first, in order to obtain number of discussions. Can we make it a simpler call or obtain it as yet another attribute in e.g. https://paperhive.org/api/documents/Ra5WnkxImoOE called 'discussion_count' and 'hive_count'? This should be quick database query. Database tables countain usualy number of tuples, so this is mostly metadata call for the database internaly to get `count`

@andrenarchy @AlexanderNaydenov

**Comment by andrenarchy** [comment]
Sure, we can add a parameter for this or a new endpoint `/documents/:id/stats` that only provides aggregated data. I think the latter would be better. What do you think?

**Comment by mrow4a** [comment]
/stat endpoint with just counts we need for widget will solve the issue :>
